version: '3'

services:

  web:
    image: lobsterk/web-nginx-php
    container_name: web-server
    restart: always
    ports:
      - "8174:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/php-fpm/php.ini:/etc/php/7.4/fpm/php.ini
      - ./.docker/php-fpm/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf

  mysql:
    image: mysql:8.0
    container_name: mydb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: r1234

  adminer:
    image: adminer
    container_name: v_adminer
    links:
      - "mysql"
    ports:
      - "8080:8080"

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=my_master_password
    ports:
      - '6379:6379'
